version: '3.9'
services:
  postgreSQL:
    image: postgres:14-alpine3.16
    container_name: sn_postgreSQL
    environment:
      POSTGRES_USER: sn_user
      POSTGRES_PASSWORD: sn_user
      POSTGRES_DB: sn_storage_service
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgreSQL/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sn_user"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
