version: '3.9'
services:
  postgreSQL:
    image: postgres:14-alpine3.16
    container_name: ${POSTGRES_HOSTNAME:-sn_postgreSQL}
    hostname: ${POSTGRES_HOSTNAME:-sn_postgreSQL}
    env_file: ./env/postgreSQL
    volumes:
      - ./postgreSQL/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sn_user"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
