spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/sn_storage_service
    username: sn_user
    password: sn_user
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  servlet:
    multipart:
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB